config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'users#new'
  resources :users
  resources :posts
  resources :sessions

  get "signup", to: "users#new", as: "signup"
  get "login", to: "sessions#new", as: "login"
  get "logout", to: "sessions#destroy", as: "logout"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :post
  validates :username, presence: true, length: { minimum: 4, maximum: 15}
  validates :mail, presence: true
  validates_uniqueness_of :mail
  validates :password, presence: true, length: { minimum: 6, maximum: 15} 
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
  before_action :authenticate_user!

  def authenticate_user!
    unless current_user
      redirect_to login_path, notice: 'Please login'
    end
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    def new
        @post = Post.new
    end

    def show
        @post = Post.find(params[:id])
    end

    def create
        @post = Post.new(post_params)

        if @post.save
            redirect_to :root
        else
            render :new
        end

    end

    def edit
        @post = Post.find(params[:id])
    end

    def update
        @post = Post.find(params[:id])

        if @post.update(post_params)
            redirect_to :root
        else
            render :edit
        end
    end

    private
    def post_params
        params.require(:post).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_user!
  
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to :root , notice: "You are logged in."
    else
      flash.now[:alert] = "Your email or password is invalid"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "You are logged out!"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:new, :create]

  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end

  def index
  end
  
  def create 
    @user = User.new(user_params)
       
    if @user.save
      redirect_to :root
    else
      render :new
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      def user_params 
        params.require(:user).permit(:username, :mail, :password, :password_confirmation)
      end
      render :edit
    end
  end  
  
  
  private
  def user_params 
    params.require(:user).permit(:username, :mail, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <p><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/edit.html.erb
<br><br>


<% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<%= form_with model: @post, url: post_path do |form| %>
    <%= form.label :post, 'Title' %>
    <%= form.text_field :title %>
    <br>
    <%= form.label :post, 'Post-body' %>
    <%= form.text_area :body %>
    <% end %>

app/views/posts/new.html.erb
<br><br>

<% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= form_with model: @post do |form| %>
<%= form.label :post, 'Title' %>
<%= form.text_field :title %>
<br>
<%= form.label :post, 'Post-body' %>
<%= form.text_area :body %>
<%= form.submit 'Submit' %>
<% end %>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


<%= form_with model: user do |form| %>

  <%= form.label :user, "Username:" %>
  <%= form.text_field :username %>

  <%= form.label :user, "Email:" %>
  <%= form.email_field  :mail %>

  <%= form.label :user, "Password:" %>
  <%= form.password_field :password %>

  <%= form.label :user, "Password Confirm" %>
    <%= form.password_field :password_confirmation %>
  
  <%= form.submit "Sign in"%>
  
<% end %>

app/views/users/edit.html.erb
<%= render 'form', user: @user %>

app/views/users/index.html.erb
<h1> index </h1>

<%= form_with model: @user do |form| %>

    <%= form.label "Username:" %>
    <%= form.text_field :username %>
  
    <%= form.label :user, "Email:" %>
    <%= form.email_field  :mail %>
  
    <%= form.label :user, "Password:" %>
    <%= form.password_field :password %>
  
    <%= form.label :user, "Password Confirm" %>
      <%= form.password_field :password_confirmation %>
    
    <%= form.submit "Sign in"%>
    
  <% end %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<br>
<br>

<%= raw @user.username %>
<%= link_to "Edit user", edit_user_path %>